name: Build MAAS-DicomTools

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:

        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup .NET 8.x
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.x'

        - name: Install dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore
